/**
 * Write src/evm/delivery-roots-artifact.ts from a fresh `forge build` of contracts/DeliveryRoots.sol, so the
 * deploy script (scripts/evm-roots-deploy.ts) sends exactly the bytecode the Solidity tests ran against.
 * test/evm-roots.test.ts builds the contract again and fails when the committed artifact differs.
 *
 *   cd contracts && forge build && cd .. && npx tsx scripts/evm-roots-artifact.ts
 */
import { readFileSync, writeFileSync } from "node:fs";

const j = JSON.parse(readFileSync("contracts/out/DeliveryRoots.sol/DeliveryRoots.json", "utf8")) as {
  bytecode: { object: string };
  deployedBytecode: { object: string; immutableReferences: Record<string, { start: number; length: number }[]> };
  rawMetadata: string;
};
const meta = JSON.parse(j.rawMetadata) as { compiler: { version: string }; settings: { evmVersion: string; optimizer: { enabled: boolean; runs: number } } };
const refs = Object.values(j.deployedBytecode.immutableReferences).flat();
const out = `/**
 * contracts/src/DeliveryRoots.sol as compiled by forge (solc ${meta.compiler.version}, evm ${meta.settings.evmVersion},
 * optimizer ${meta.settings.optimizer.runs} runs). Generated by scripts/evm-roots-artifact.ts; do not edit by hand.
 * \`runtime\` has the immutable \`writer\` zeroed at \`writerOffsets\` (bytes into the runtime code).
 */
export const DELIVERY_ROOTS_ARTIFACT = {
  solc: ${JSON.stringify(meta.compiler.version)},
  evmVersion: ${JSON.stringify(meta.settings.evmVersion)},
  optimizerRuns: ${meta.settings.optimizer.runs},
  creation: ${JSON.stringify(j.bytecode.object)},
  runtime: ${JSON.stringify(j.deployedBytecode.object)},
  writerOffsets: ${JSON.stringify(refs.map((r) => r.start))},
} as const;
`;
writeFileSync("src/evm/delivery-roots-artifact.ts", out);
console.log(`src/evm/delivery-roots-artifact.ts: creation ${(j.bytecode.object.length - 2) / 2} bytes, runtime ${(j.deployedBytecode.object.length - 2) / 2} bytes`);
